source "https://rubygems.org"

gem "rails", "4.2.3"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "bootstrap-sass", "3.2.0.0"
gem "bootstrap-datepicker-rails"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "settingslogic"
gem "devise"
gem "cancancan"
gem "ransack"
gem "draper"
gem "kaminari"
gem "mysql2", "~> 0.3.20"
gem "delayed_job_active_record"
gem "sidekiq"
gem "whenever", require: false
gem "i18n-js", ">= 3.0.0.rc11"
gem "routing-filter"
gem "public_activity"
gem "ckeditor"
gem "carrierwave"
gem "mini_magick"
gem "jquery-ui-rails"
gem "ranked-model"
gem "highcharts-rails"

group :development, :test do
  gem "fabrication"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "pry"
  gem "letter_opener"
  gem "faker", "1.4.2"
  gem "i18n-tasks", "~> 0.8.7"
  gem "rspec-rails", "~> 3.0"
end
