source "https://rubygems.org"

gem "rails", "~> 5.0.0"
gem "puma", "~> 3.0"
gem "redis", "~> 3.0"
gem "activemodel-serializers-xml", git: "https://github.com/rails/activemodel-serializers-xml"
gem "routing-filter", github: "svenfuchs/routing-filter", branch: "master"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "bootstrap-sass", "3.2.0.0"
gem "bootstrap-datepicker-rails"
gem "jquery-rails"
gem "turbolinks", "~> 5"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "settingslogic"
gem "devise"
gem "cancancan"
gem "ransack"
gem "draper", github: "audionerd/draper", branch: "rails5"
gem "kaminari"
gem "bootstrap-kaminari-views"
gem "mysql2", "~> 0.3.20"
gem "delayed_job_active_record"
gem "sidekiq"
gem "whenever", require: false
gem "i18n-js", ">= 3.0.0.rc11"
gem "public_activity"
gem "ckeditor"
gem "carrierwave"
gem "mini_magick"
gem "jquery-ui-rails"
gem "ranked-model"
gem "highcharts-rails"
gem "ajax-datatables-rails", "0.1.2"
gem "jquery-datatables-rails", github: "rweng/jquery-datatables-rails"
gem "breadcrumbs_on_rails"
gem "font-awesome-rails"
group :development, :test do
  gem "fabrication"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "pry"
  gem "letter_opener"
  gem "faker", "1.4.2"
  gem "i18n-tasks", "~> 0.8.7"
  gem "rspec-rails", "~> 3.0"
end
